### ISSUE TITLE
Destroying a User does not redirect to the homepage

### ISSUE THREAD

**Issue by kinifi** [kinifi/poly-RoR-server#1]
If you destroy a user from admin console or if the user destroy's themselves, they will be redirected to view the user instead of the homepage after deleting from the database.

**Comment by ManuelCostanzo** [comment]
Hello

In file users_controller on line 65, change:

`    respond_to do |format|
      redirect_to home_path , notice: "Success"
    end`

to

`redirect_to home_path , notice: "Success"`

**Comment by kinifi** [comment]
fixed it!! Thank you so much!! [here is the fix](https://github.com/kinifi/poly-RoR-server/commit/c2bb13685c27194d980c202a4a7785828fb08807)
