### ISSUE TITLE
nav doesn't work when on mobile

### ISSUE THREAD

**Issue by kinifi** [kinifi/poly-RoR-server#7]
I used the following: http://codepen.io/macsupport/pen/bKFzD?editors=1100

for some reason it doesn't collapse and open up on mobile even though my page is exactly the same

**Comment by kinifi** [comment]
Here is the code for the nav https://github.com/kinifi/poly-RoR-server/blob/master/app/views/layouts/_header.html.erb

**Comment by BretHudson** [comment]
Make sure you're including jQuery and the Bootstrap JavaScript files:
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
```

**Comment by kinifi** [comment]
Nope wasn't that. Both of those are included... hmmmm

**Comment by kinifi** [comment]
Thanks it was that! I thought it wasn't but apparently I just wasn't understanding the JS pipeline for Ruby on Rails. I got it working though! Thank you! The menu should now work on mobile!
